In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
x_ones = torch.ones_like(x_data)
print(f'Ones tensor: {x_ones}')

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'Random tensor: {x_rand}')

Ones tensor: tensor([[1, 1],
        [1, 1]])
Random tensor: tensor([[0.9297, 0.5550],
        [0.3662, 0.0825]])


In [15]:
shape = (2, 4)
rand_tensor = torch.rand(shape)
print(f'Random tensor with shape {shape}:\n {rand_tensor}')

print(f'\nFirst row of the tensor: {rand_tensor[0]}')
print(f'First column of the tensor: {rand_tensor[:, 0]}')
print(f'First element of the tensor: {rand_tensor[0, 0]}')
print(f'Last column of the tensor: {rand_tensor[..., -1]}')

Random tensor with shape (2, 4):
 tensor([[0.2501, 0.2947, 0.4492, 0.8659],
        [0.3582, 0.9465, 0.6559, 0.8453]])

First row of the tensor: tensor([0.2501, 0.2947, 0.4492, 0.8659])
First column of the tensor: tensor([0.2501, 0.3582])
First element of the tensor: 0.25006914138793945
Last column of the tensor: tensor([0.8659, 0.8453])


In [35]:
torch.cat([rand_tensor, rand_tensor], dim=1)

tensor([[0.2501, 0.2947, 0.4492, 0.8659, 0.2501, 0.2947, 0.4492, 0.8659],
        [0.3582, 0.9465, 0.6559, 0.8453, 0.3582, 0.9465, 0.6559, 0.8453]])

In [36]:
tensor = torch.rand(3, 4)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.8610, 0.3298, 0.8313, 0.2718],
        [0.7871, 0.8275, 0.3418, 0.0104],
        [0.6685, 0.6715, 0.0333, 0.2026]])

In [37]:
agg = tensor.sum().item()
print(f'Aggregate function: {agg}')

print(f'Aggregate function item and type: {agg} {type(agg)}')

Aggregate function: 7.6881794929504395
Aggregate function item and type: 7.6881794929504395 <class 'float'>
